### PR TITLE
Fix column names in data_to_wide()

### LINKED ISSUE #173: `data_to_wide()` produces wrong column names?
I'd expect `data_to_wide()` to use those values we find the the specified column as new column names, but instead it concatenates the _name + values_ of the specified column.

``` r
library(datawizard)
wide_data <- data.frame(replicate(5, rnorm(10)))
head(wide_data)
#>           X1          X2         X3         X4         X5
#> 1  1.5524351 -0.48444918  1.2965414  1.5748509  0.9066197
#> 2  1.3487543  0.38939599  0.9098696  1.6512472  0.2379350
#> 3  0.6093308 -0.29823544 -1.1845217 -0.1488228 -1.3633194
#> 4 -0.9935626  0.28795097  0.4787015 -0.1077735  0.4394244
#> 5 -0.1388012 -0.04156177  1.5174289  0.2450672 -0.3095916
#> 6 -1.4821222 -0.52842663 -0.1319516  0.6831677 -1.4638114

long_data <- data_to_long(wide_data,
                          select = c(1, 2),
                          colnames_to = "Column",
                          values_to = "Numbers")

head(long_data)
#>           X3         X4         X5 Column    Numbers
#> 1  1.2965414  1.5748509  0.9066197     X1  1.5524351
#> 2  1.2965414  1.5748509  0.9066197     X2 -0.4844492
#> 3  0.9098696  1.6512472  0.2379350     X1  1.3487543
#> 4  0.9098696  1.6512472  0.2379350     X2  0.3893960
#> 5 -1.1845217 -0.1488228 -1.3633194     X1  0.6093308
#> 6 -1.1845217 -0.1488228 -1.3633194     X2 -0.2982354

# column names should be X1 to X5? not "Numbers_X1", but "X1"
data_to_wide(long_data, values_from = "Numbers", colnames_from = "Column") |> 
  head()
#>           X3         X4         X5 Numbers_X1  Numbers_X2
#> 1  1.2965414  1.5748509  0.9066197  1.5524351 -0.48444918
#> 2  0.9098696  1.6512472  0.2379350  1.3487543  0.38939599
#> 3 -1.1845217 -0.1488228 -1.3633194  0.6093308 -0.29823544
#> 4  0.4787015 -0.1077735  0.4394244 -0.9935626  0.28795097
#> 5  1.5174289  0.2450672 -0.3095916 -0.1388012 -0.04156177
#> 6 -0.1319516  0.6831677 -1.4638114 -1.4821222 -0.52842663
```

<sup>Created on 2022-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by strengejacke**
close #173

### CODE REVIEW

**Comment by bwiernik** [comment]
While you are working on this, could you also update `rows_to` to use rownames if present rather than always the number?

**Review by IndrajeetPatil — APPROVED** [review]

**Comment by strengejacke** [comment]
> While you are working on this, could you also update `rows_to` to use rownames if present rather than always the number?

`rows_to` uses names, when present. It's just that either row numbers or names are put into a new column, while the returned data frame itself has no rownames:

``` r
library(datawizard)
data(mtcars)
mtcars
#>                      mpg cyl  disp  hp drat    wt  qsec vs am gear carb
#> Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
#> Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
#> Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
#> Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
#> Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
#> Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
#> Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
#> Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
#> Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
#> Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
#> Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
#> Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
#> Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
#> Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
#> Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
#> Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
#> Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
#> Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
#> Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
#> Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
#> Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
#> AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
#> Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
#> Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
#> Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
#> Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
#> Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
#> Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
#> Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
#> Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8
#> Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2

data_to_long(
  mtcars,
  select = c("gear", "carb"),
  colnames_to = "cnames",
  values_to = "Value"
)
#>     mpg cyl  disp  hp drat    wt  qsec vs am cnames Value
#> 1  15.2   8 304.0 150 3.15 3.435 17.30  0  0   gear     3
#> 2  15.2   8 304.0 150 3.15 3.435 17.30  0  0   carb     2
#> 3  10.4   8 472.0 205 2.93 5.250 17.98  0  0   gear     3
#> 4  10.4   8 472.0 205 2.93 5.250 17.98  0  0   carb     4
#> 5  13.3   8 350.0 245 3.73 3.840 15.41  0  0   gear     3
#> 6  13.3   8 350.0 245 3.73 3.840 15.41  0  0   carb     4
#> 7  14.7   8 440.0 230 3.23 5.345 17.42  0  0   gear     3
#> 8  14.7   8 440.0 230 3.23 5.345 17.42  0  0   carb     4
#> 9  22.8   4 108.0  93 3.85 2.320 18.61  1  1   gear     4
#> 10 22.8   4 108.0  93 3.85 2.320 18.61  1  1   carb     1
#> 11 15.5   8 318.0 150 2.76 3.520 16.87  0  0   gear     3
#> 12 15.5   8 318.0 150 2.76 3.520 16.87  0  0   carb     2
#> 13 14.3   8 360.0 245 3.21 3.570 15.84  0  0   gear     3
#> 14 14.3   8 360.0 245 3.21 3.570 15.84  0  0   carb     4
#> 15 19.7   6 145.0 175 3.62 2.770 15.50  0  1   gear     5
#> 16 19.7   6 145.0 175 3.62 2.770 15.50  0  1   carb     6
#> 17 32.4   4  78.7  66 4.08 2.200 19.47  1  1   gear     4
#> 18 32.4   4  78.7  66 4.08 2.200 19.47  1  1   carb     1
#> 19 27.3   4  79.0  66 4.08 1.935 18.90  1  1   gear     4
#> 20 27.3   4  79.0  66 4.08 1.935 18.90  1  1   carb     1
#> 21 15.8   8 351.0 264 4.22 3.170 14.50  0  1   gear     5
#> 22 15.8   8 351.0 264 4.22 3.170 14.50  0  1   carb     4
#> 23 30.4   4  75.7  52 4.93 1.615 18.52  1  1   gear     4
#> 24 30.4   4  75.7  52 4.93 1.615 18.52  1  1   carb     2
#> 25 21.4   6 258.0 110 3.08 3.215 19.44  1  0   gear     3
#> 26 21.4   6 258.0 110 3.08 3.215 19.44  1  0   carb     1
#> 27 18.7   8 360.0 175 3.15 3.440 17.02  0  0   gear     3
#> 28 18.7   8 360.0 175 3.15 3.440 17.02  0  0   carb     2
#> 29 10.4   8 460.0 215 3.00 5.424 17.82  0  0   gear     3
#> 30 10.4   8 460.0 215 3.00 5.424 17.82  0  0   carb     4
#> 31 30.4   4  95.1 113 3.77 1.513 16.90  1  1   gear     5
#> 32 30.4   4  95.1 113 3.77 1.513 16.90  1  1   carb     2
#> 33 15.0   8 301.0 335 3.54 3.570 14.60  0  1   gear     5
#> 34 15.0   8 301.0 335 3.54 3.570 14.60  0  1   carb     8
#> 35 21.0   6 160.0 110 3.90 2.620 16.46  0  1   gear     4
#> 36 21.0   6 160.0 110 3.90 2.620 16.46  0  1   carb     4
#> 37 21.0   6 160.0 110 3.90 2.875 17.02  0  1   gear     4
#> 38 21.0   6 160.0 110 3.90 2.875 17.02  0  1   carb     4
#> 39 22.8   4 140.8  95 3.92 3.150 22.90  1  0   gear     4
#> 40 22.8   4 140.8  95 3.92 3.150 22.90  1  0   carb     2
#> 41 24.4   4 146.7  62 3.69 3.190 20.00  1  0   gear     4
#> 42 24.4   4 146.7  62 3.69 3.190 20.00  1  0   carb     2
#> 43 19.2   6 167.6 123 3.92 3.440 18.30  1  0   gear     4
#> 44 19.2   6 167.6 123 3.92 3.440 18.30  1  0   carb     4
#> 45 17.8   6 167.6 123 3.92 3.440 18.90  1  0   gear     4
#> 46 17.8   6 167.6 123 3.92 3.440 18.90  1  0   carb     4
#> 47 16.4   8 275.8 180 3.07 4.070 17.40  0  0   gear     3
#> 48 16.4   8 275.8 180 3.07 4.070 17.40  0  0   carb     3
#> 49 17.3   8 275.8 180 3.07 3.730 17.60  0  0   gear     3
#> 50 17.3   8 275.8 180 3.07 3.730 17.60  0  0   carb     3
#> 51 15.2   8 275.8 180 3.07 3.780 18.00  0  0   gear     3
#> 52 15.2   8 275.8 180 3.07 3.780 18.00  0  0   carb     3
#> 53 19.2   8 400.0 175 3.08 3.845 17.05  0  0   gear     3
#> 54 19.2   8 400.0 175 3.08 3.845 17.05  0  0   carb     2
#> 55 26.0   4 120.3  91 4.43 2.140 16.70  0  1   gear     5
#> 56 26.0   4 120.3  91 4.43 2.140 16.70  0  1   carb     2
#> 57 33.9   4  71.1  65 4.22 1.835 19.90  1  1   gear     4
#> 58 33.9   4  71.1  65 4.22 1.835 19.90  1  1   carb     1
#> 59 21.5   4 120.1  97 3.70 2.465 20.01  1  0   gear     3
#> 60 21.5   4 120.1  97 3.70 2.465 20.01  1  0   carb     1
#> 61 18.1   6 225.0 105 2.76 3.460 20.22  1  0   gear     3
#> 62 18.1   6 225.0 105 2.76 3.460 20.22  1  0   carb     1
#> 63 21.4   4 121.0 109 4.11 2.780 18.60  1  1   gear     4
#> 64 21.4   4 121.0 109 4.11 2.780 18.60  1  1   carb     2

data_to_long(
  mtcars,
  select = c("gear", "carb"),
  colnames_to = "cnames",
  values_to = "Value",
  rows_to = "rwn"
)
#>     mpg cyl  disp  hp drat    wt  qsec vs am                 rwn cnames Value
#> 1  15.2   8 304.0 150 3.15 3.435 17.30  0  0         AMC Javelin   gear     3
#> 2  15.2   8 304.0 150 3.15 3.435 17.30  0  0         AMC Javelin   carb     2
#> 3  10.4   8 472.0 205 2.93 5.250 17.98  0  0  Cadillac Fleetwood   gear     3
#> 4  10.4   8 472.0 205 2.93 5.250 17.98  0  0  Cadillac Fleetwood   carb     4
#> 5  13.3   8 350.0 245 3.73 3.840 15.41  0  0          Camaro Z28   gear     3
#> 6  13.3   8 350.0 245 3.73 3.840 15.41  0  0          Camaro Z28   carb     4
#> 7  14.7   8 440.0 230 3.23 5.345 17.42  0  0   Chrysler Imperial   gear     3
#> 8  14.7   8 440.0 230 3.23 5.345 17.42  0  0   Chrysler Imperial   carb     4
#> 9  22.8   4 108.0  93 3.85 2.320 18.61  1  1          Datsun 710   gear     4
#> 10 22.8   4 108.0  93 3.85 2.320 18.61  1  1          Datsun 710   carb     1
#> 11 15.5   8 318.0 150 2.76 3.520 16.87  0  0    Dodge Challenger   gear     3
#> 12 15.5   8 318.0 150 2.76 3.520 16.87  0  0    Dodge Challenger   carb     2
#> 13 14.3   8 360.0 245 3.21 3.570 15.84  0  0          Duster 360   gear     3
#> 14 14.3   8 360.0 245 3.21 3.570 15.84  0  0          Duster 360   carb     4
#> 15 19.7   6 145.0 175 3.62 2.770 15.50  0  1        Ferrari Dino   gear     5
#> 16 19.7   6 145.0 175 3.62 2.770 15.50  0  1        Ferrari Dino   carb     6
#> 17 32.4   4  78.7  66 4.08 2.200 19.47  1  1            Fiat 128   gear     4
#> 18 32.4   4  78.7  66 4.08 2.200 19.47  1  1            Fiat 128   carb     1
#> 19 27.3   4  79.0  66 4.08 1.935 18.90  1  1           Fiat X1-9   gear     4
#> 20 27.3   4  79.0  66 4.08 1.935 18.90  1  1           Fiat X1-9   carb     1
#> 21 15.8   8 351.0 264 4.22 3.170 14.50  0  1      Ford Pantera L   gear     5
#> 22 15.8   8 351.0 264 4.22 3.170 14.50  0  1      Ford Pantera L   carb     4
#> 23 30.4   4  75.7  52 4.93 1.615 18.52  1  1         Honda Civic   gear     4
#> 24 30.4   4  75.7  52 4.93 1.615 18.52  1  1         Honda Civic   carb     2
#> 25 21.4   6 258.0 110 3.08 3.215 19.44  1  0      Hornet 4 Drive   gear     3
#> 26 21.4   6 258.0 110 3.08 3.215 19.44  1  0      Hornet 4 Drive   carb     1
#> 27 18.7   8 360.0 175 3.15 3.440 17.02  0  0   Hornet Sportabout   gear     3
#> 28 18.7   8 360.0 175 3.15 3.440 17.02  0  0   Hornet Sportabout   carb     2
#> 29 10.4   8 460.0 215 3.00 5.424 17.82  0  0 Lincoln Continental   gear     3
#> 30 10.4   8 460.0 215 3.00 5.424 17.82  0  0 Lincoln Continental   carb     4
#> 31 30.4   4  95.1 113 3.77 1.513 16.90  1  1        Lotus Europa   gear     5
#> 32 30.4   4  95.1 113 3.77 1.513 16.90  1  1        Lotus Europa   carb     2
#> 33 15.0   8 301.0 335 3.54 3.570 14.60  0  1       Maserati Bora   gear     5
#> 34 15.0   8 301.0 335 3.54 3.570 14.60  0  1       Maserati Bora   carb     8
#> 35 21.0   6 160.0 110 3.90 2.620 16.46  0  1           Mazda RX4   gear     4
#> 36 21.0   6 160.0 110 3.90 2.620 16.46  0  1           Mazda RX4   carb     4
#> 37 21.0   6 160.0 110 3.90 2.875 17.02  0  1       Mazda RX4 Wag   gear     4
#> 38 21.0   6 160.0 110 3.90 2.875 17.02  0  1       Mazda RX4 Wag   carb     4
#> 39 22.8   4 140.8  95 3.92 3.150 22.90  1  0            Merc 230   gear     4
#> 40 22.8   4 140.8  95 3.92 3.150 22.90  1  0            Merc 230   carb     2
#> 41 24.4   4 146.7  62 3.69 3.190 20.00  1  0           Merc 240D   gear     4
#> 42 24.4   4 146.7  62 3.69 3.190 20.00  1  0           Merc 240D   carb     2
#> 43 19.2   6 167.6 123 3.92 3.440 18.30  1  0            Merc 280   gear     4
#> 44 19.2   6 167.6 123 3.92 3.440 18.30  1  0            Merc 280   carb     4
#> 45 17.8   6 167.6 123 3.92 3.440 18.90  1  0           Merc 280C   gear     4
#> 46 17.8   6 167.6 123 3.92 3.440 18.90  1  0           Merc 280C   carb     4
#> 47 16.4   8 275.8 180 3.07 4.070 17.40  0  0          Merc 450SE   gear     3
#> 48 16.4   8 275.8 180 3.07 4.070 17.40  0  0          Merc 450SE   carb     3
#> 49 17.3   8 275.8 180 3.07 3.730 17.60  0  0          Merc 450SL   gear     3
#> 50 17.3   8 275.8 180 3.07 3.730 17.60  0  0          Merc 450SL   carb     3
#> 51 15.2   8 275.8 180 3.07 3.780 18.00  0  0         Merc 450SLC   gear     3
#> 52 15.2   8 275.8 180 3.07 3.780 18.00  0  0         Merc 450SLC   carb     3
#> 53 19.2   8 400.0 175 3.08 3.845 17.05  0  0    Pontiac Firebird   gear     3
#> 54 19.2   8 400.0 175 3.08 3.845 17.05  0  0    Pontiac Firebird   carb     2
#> 55 26.0   4 120.3  91 4.43 2.140 16.70  0  1       Porsche 914-2   gear     5
#> 56 26.0   4 120.3  91 4.43 2.140 16.70  0  1       Porsche 914-2   carb     2
#> 57 33.9   4  71.1  65 4.22 1.835 19.90  1  1      Toyota Corolla   gear     4
#> 58 33.9   4  71.1  65 4.22 1.835 19.90  1  1      Toyota Corolla   carb     1
#> 59 21.5   4 120.1  97 3.70 2.465 20.01  1  0       Toyota Corona   gear     3
#> 60 21.5   4 120.1  97 3.70 2.465 20.01  1  0       Toyota Corona   carb     1
#> 61 18.1   6 225.0 105 2.76 3.460 20.22  1  0             Valiant   gear     3
#> 62 18.1   6 225.0 105 2.76 3.460 20.22  1  0             Valiant   carb     1
#> 63 21.4   4 121.0 109 4.11 2.780 18.60  1  1          Volvo 142E   gear     4
#> 64 21.4   4 121.0 109 4.11 2.780 18.60  1  1          Volvo 142E   carb     2
```

<sup>Created on 2022-06-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

File: R/data_reshape.R [hunk 1]
```diff
@@ -13,9 +13,9 @@
 #' @param rows_to The name of the column that will contain the row-number from
```
Comment (bwiernik) [inline R/data_reshape.R:13]: Could you modify this to say "row names or row numbers"?

**Review by bwiernik — CHANGES_REQUESTED** [review]
