### PR TITLE
Possible bug when requesting multiple indices of centrality in `describe_distribution()`

### LINKED ISSUE #616: Possible bug when requesting multiple indices of centrality in `describe_distribution()`
According to the help files `describe_distribution()` should be able to take a character vector to the `centrality` argument:

```
The point-estimates (centrality indices) to compute. Character (vector) or list with one or more of these options: "median", "mean", "MAP" (see [map_estimate()](https://easystats.github.io/bayestestR/reference/map_estimate.html)), "trimmed" (which is just mean(x, trim = threshold)), "mode" or "all".
```

Using a single index of centrality works fine:

```
puppy_tib <- discovr::puppies

describe_distribution(x = puppy_tib,
                      select = "happiness",
                      centrality = "median")

describe_distribution(x = puppy_tib,
                      select = "happiness",
                      centrality = "mean")
```

However, if I specify more than one index the function throws an error. For example:

```
describe_distribution(x = puppy_tib,
                      select = "happiness",
                      centrality = c("median", "mean"))
```

Image

Is this a bug or user-error?

Session info:

```
R version 4.4.3 (2025-02-28)
Platform: x86_64-apple-darwin20
Running under: macOS Sequoia 15.3.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/London
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] effectsize_1.0.0.1  lubridate_1.9.4     forcats_1.0.0       stringr_1.5.1       dplyr_1.1.4         purrr_1.0.4         readr_2.1.5        
 [8] tidyr_1.3.1         tibble_3.2.1        ggplot2_3.5.2       tidyverse_2.0.0     see_0.11.0          report_0.6.1        parameters_0.24.2  
[15] performance_0.13.0  modelbased_0.10.0   insight_1.1.0.38    datawizard_1.0.2.12 correlation_0.8.7   bayestestR_0.15.2   easystats_0.7.4    

loaded via a namespace (and not attached):
  [1] splines_4.4.3           later_1.4.2             palmerpenguins_0.1.1    bitops_1.0-9            rpart_4.1.24            lifecycle_1.0.4        
  [7] Rdpack_2.6.4            pbmcapply_1.5.1         doParallel_1.0.17       rprojroot_2.0.4         globals_0.16.3          processx_3.8.6         
 [13] lattice_0.22-7          vroom_1.6.5             MASS_7.3-65             backports_1.5.0         magrittr_2.0.3          Hmisc_5.2-3            
 [19] rmarkdown_2.29          yaml_2.3.10             qqplotr_0.0.6           remotes_2.5.0           qqconf_1.3.2            httpuv_1.6.15          
 [25] pkgbuild_1.4.7          minqa_1.2.8             pbapply_1.7-2           RColorBrewer_1.1-3      multcomp_1.4-28         pkgload_1.4.0          
 [31] quadprog_1.5-8          nnet_7.3-20             pracma_2.4.4            TH.data_1.1-3           sandwich_3.1-1          jtools_2.3.0           
 [37] ggrepel_0.9.6           listenv_0.9.1           MatrixModels_0.5-4      parallelly_1.43.0       codetools_0.2-20        shape_1.4.6.1          
 [43] tidyselect_1.2.1        farver_2.1.2            lme4_1.1-37             broom.mixed_0.2.9.6     WRS2_1.1-6              stats4_4.4.3           
 [49] base64enc_0.1-3         jsonlite_2.0.0          opdisDownsampling_1.0.1 mitml_0.4-5             Formula_1.2-5           survival_3.8-3         
 [55] iterators_1.0.14        emmeans_1.11.0          foreach_1.5.2           tools_4.4.3             twosamples_2.0.1        Rcpp_1.0.14            
 [61] glue_1.8.0              pan_1.9                 mnormt_2.1.1            gridExtra_2.3           xfun_0.52               here_1.0.1             
 [67] mgcv_1.9-3              withr_3.0.2             fastmap_1.2.0           GGally_2.2.1            boot_1.3-31             callr_3.7.6            
 [73] caTools_1.18.3          digest_0.6.37           timechange_0.3.0        R6_2.6.1                mime_0.13               estimability_1.5.1     
 [79] mice_3.17.0             colorspace_2.1-1        generics_0.1.3          renv_1.1.4              data.table_1.17.0       robustbase_0.99-4-1    
 [85] htmlwidgets_1.6.4       ggstats_0.9.0           pkgconfig_2.0.3         gtable_0.3.6            robust_0.7-5            rsconnect_1.3.4        
 [91] BayesFactor_0.9.12-4.7  pcaPP_2.0-5             furrr_0.3.1             htmltools_0.5.8.1       lavaan_0.6-19           interactions_1.2.0     
 [97] scales_1.3.0            reformulas_0.4.0        knitr_1.50              rstudioapi_0.17.1       tzdb_0.5.0              nloptr_2.2.1           
[103] coda_0.19-4.1           checkmate_2.3.2         nlme_3.1-168            curl_6.2.2              zoo_1.8-13              parallel_4.4.3         
[109] foreign_0.8-90          desc_1.4.3              pillar_1.10.2           grid_4.4.3              reshape_0.8.9           vctrs_0.6.5            
[115] promises_1.3.2          jomo_2.7-6              xtable_1.8-4            cluster_2.1.8.1         htmlTable_2.4.3         evaluate_1.0.3         
[121] pbivnorm_0.6.0          mvtnorm_1.3-3           cli_3.6.4               compiler_4.4.3          rlang_1.1.6             crayon_1.5.3           
[127] rstantools_2.4.0        rrcov_1.7-6             labeling_0.4.3          ps_1.9.0                plyr_1.8.9              stringi_1.8.7          
[133] pander_0.6.6            quarto_1.4.4            munsell_0.5.1           fit.models_0.64         marginaleffects_0.25.1  glmnet_4.1-8           
[139] Matrix_1.7-3            hms_1.1.3               patchwork_1.3.0         bit64_4.6.0-1           future_1.34.0           learnr_0.11.5.9000     
[145] shiny_1.10.0            rbibutils_2.3           broom_1.0.8             RcppParallel_5.1.10     discovr_0.2.0.2         DEoptimR_1.1-3-1       
[151] bit_4.6.0    
```

### LINKED ISSUE #618: `describe_distribution()` doesn't reduce verbosity even when `verbose = FALSE`
``` r
data <- dplyr::filter(ggplot2::mpg, cyl == "4", manufacturer == "chevrolet")
datawizard::describe_distribution(data[["cty"]], centrality = "MAP", ci = 0.95, verbose = FALSE)
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> Data is singular, MAP estimate equals the unique value of the data.
#> Warning: Need at least 3 complete observations for type-2-skewness. Using
#>   'type="1"' now.
#> Warning: Need at least 4 complete observations for type-2-kurtosis Using
#>   'type="1"' now.
#> MAP | IQR |         95% CI |          Range | Skewness | Kurtosis | n | n_Missing
#> ---------------------------------------------------------------------------------
#>  19 |   3 | [19.00, 22.00] | [19.00, 22.00] |        0 |       -2 | 2 |         0
```

<sup>Created on 2025-04-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by strengejacke**
Fixes #616
Fixes #618

### CODE REVIEW

File: tests/testthat/test-describe_distribution.R [hunk 1]
```diff
@@ -351,3 +351,34 @@ test_that("errors on invalid column names (reserved word)", {
     regex = "Following variable names are reserved"
   )
 })
+
+# multiple centralities
+test_that("multiple centralities work", {
```
Comment (etiennebacher) [inline tests/testthat/test-describe_distribution.R:356]: Maybe you were already planning to add them, but can we also test with `ci = 0.95` for instance to check that the output with multiple CI columns is fine?

**Comment by strengejacke** [comment]
@etiennebacher @DominiqueMakowski I think the latest changes in _bayestestR_ will break tests in _datawizard_. _insight_ is on CRAN, but no revdep-issues. But _bayestestR_ would be next, and I'm pretty sure this breaks the CRAN version of datawizard.

**Comment by IndrajeetPatil** [comment]
Does this also fix https://github.com/easystats/datawizard/issues/618 by any chance?

**Comment by strengejacke** [comment]
Yes:

``` r
data <- dplyr::filter(ggplot2::mpg, cyl == "4", manufacturer == "chevrolet")
datawizard::describe_distribution(data[["cty"]], centrality = "MAP", ci = 0.95, verbose = FALSE)
#> MAP |   95% CI (MAP) | IQR |          Range | Skewness | Kurtosis | n | n_Missing
#> ---------------------------------------------------------------------------------
#>  19 | [19.00, 22.00] |   3 | [19.00, 22.00] |        0 |       -2 | 2 |         0
```

<sup>Created on 2025-04-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Review by etiennebacher — APPROVED** [review]
Thanks, LGTM

**Review by etiennebacher — CHANGES_REQUESTED** [review]
Ah but some R CMD check workflows are failing?

**Comment by IndrajeetPatil** [comment]
> Ah but some R CMD check workflows are failing?

We need to run relevant `describe_distribution()` tests relying on `{bayestestR}` conditional on its availability because it's an optional dependency.

File: tests/testthat/test-describe_distribution.R [hunk 2]
```diff
@@ -349,6 +349,7 @@ test_that("multiple centralities work", {
 
 
 test_that("(multiple) centralities with CIs", {
+  skip_if_not_installed("bayestestR")
```
Comment (strengejacke) [inline tests/testthat/test-describe_distribution.R:352]: I added this to the top of the file, because we literally used this in every test.

**Comment by etiennebacher** [comment]
Seems there is a numerical failure in one of the new tests but only for some versions of R, do you know why?

File: tests/testthat/test-describe_distribution.R (hunk 2 above)
Comment (strengejacke) [reply tests/testthat/test-describe_distribution.R]: agree, but we had this skip in 95% of all tests, so I thought it is probably ok to run this test only if bayestestR is available.

**Comment by strengejacke** [comment]
I think we had this issue a few times, density estimation (for different methods) seems to differ depending on the OS? I'd say we change the tolerance.

**Comment by IndrajeetPatil** [comment]
@etiennebacher and @strengejacke This will break both `{statsExpressions}` and `{ggstatsplot}`. But I have already fixed the breakages on GitHub.

When you submit to CRAN, make sure to include this details in CRAN comments.

**Comment by etiennebacher** [comment]
Thanks for the heads-up!
